# Generated by Django 3.2.5 on 2023-09-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0027_nkflocality_terminal_unit_count'),
        ('freshwaterfish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='froccurrence',
            name='age_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='age_code', to='nkfcluster.chronounit'),
        ),
        migrations.AddField(
            model_name='froccurrence',
            name='epoch_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='epoch_code', to='nkfcluster.chronounit'),
        ),
        migrations.AddField(
            model_name='froccurrence',
            name='period_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='period_code', to='nkfcluster.chronounit'),
        ),
    ]
