# Generated by Django 3.2.5 on 2023-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshwaterfish', '0002_auto_20230901_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='froccurrence',
            name='environment_code',
            field=models.CharField(blank=True, choices=[('01', 'lacustrine'), ('02', 'channel'), ('03', 'pond'), ('04', 'floodplain'), ('05', 'terrestrial'), ('06', 'fluvial-lacustrine'), ('07', 'bay'), ('08', 'fluvial')], max_length=10, null=True),
        ),
    ]
