# Generated by Django 3.2.5 on 2024-09-13 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshwaterfish', '0003_froccurrence_environment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='freshwaterfish/files/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='froccurrence',
            name='frfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freshwaterfish.frfile'),
        ),
    ]
