# Generated by Django 3.2.5 on 2022-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylouser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phylouser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
