# Generated by Django 3.2.5 on 2022-04-25 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0002_auto_20220425_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylorun',
            name='datatype',
            field=models.CharField(blank=True, choices=[('MO', 'Morphology'), ('DN', 'DNA'), ('RN', 'RNA'), ('AA', 'Amino acid')], default='MO', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phylorun',
            name='run_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
