# Generated by Django 3.2.5 on 2022-04-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0003_auto_20220425_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhyloRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procid', models.CharField(blank=True, max_length=20, null=True)),
                ('runner_status', models.CharField(blank=True, choices=[('ST', 'Starting'), ('SL', 'Sleeping'), ('WK', 'Working'), ('FN', 'Finished')], max_length=20, null=True)),
                ('command', models.CharField(blank=True, max_length=20, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phylouser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='phylouser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='성'),
        ),
        migrations.CreateModel(
            name='PhyloAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_status', models.CharField(blank=True, choices=[('IP', 'In progress'), ('FN', 'Finished'), ('ER', 'Error occurred')], max_length=20, null=True)),
                ('log_text', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_set', to='phylomanager.phyloleg')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_set', to='phylomanager.phylorunner')),
            ],
        ),
    ]
