# Generated by Django 3.2.5 on 2022-05-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0004_auto_20220427_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhyloData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(blank=True, max_length=200, null=True)),
                ('datatype', models.CharField(blank=True, choices=[('MO', 'Morphology'), ('DN', 'DNA'), ('RN', 'RNA'), ('AA', 'Amino acid')], default='MO', max_length=10, null=True)),
                ('n_taxa', models.IntegerField(blank=True, null=True)),
                ('n_chars', models.IntegerField(blank=True, null=True)),
                ('taxa_list', models.TextField(blank=True, null=True)),
                ('char_list', models.TextField(blank=True, null=True)),
                ('datamatrix_json', models.TextField(blank=True, null=True)),
                ('mrbayes_block', models.TextField(blank=True, null=True)),
                ('nexus_command_json', models.TextField(blank=True, null=True)),
                ('filetext', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phyloleg',
            name='ml_bootstrap',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='phyloleg',
            name='ml_bootstrap_type',
            field=models.CharField(blank=True, choices=[('NB', 'Normal Bootstrap'), ('UF', 'Ultra Fast Bootstrap(IQTree)')], default='NB', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phylorun',
            name='phylodata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phylomanager.phylodata'),
        ),
    ]
