# Generated by Django 3.2.5 on 2022-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0005_auto_20220503_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phylodata',
            old_name='char_list',
            new_name='character_definition_hash_json',
        ),
        migrations.RenameField(
            model_name='phylodata',
            old_name='filetext',
            new_name='file_wholetext',
        ),
        migrations.RenameField(
            model_name='phylodata',
            old_name='taxa_list',
            new_name='taxa_list_json',
        ),
        migrations.AddField(
            model_name='phylodata',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phylodata',
            name='matrix_settings_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
