# Generated by Django 3.2.5 on 2022-05-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0006_auto_20220503_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phylodata',
            old_name='nexus_command_json',
            new_name='nexus_command_hash_json',
        ),
    ]
