# Generated by Django 3.2.5 on 2022-05-09 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phylomanager', '0007_rename_nexus_command_json_phylodata_nexus_command_hash_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='phyloanalog',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_set', to='phylomanager.phylorun'),
        ),
        migrations.AddField(
            model_name='phyloleg',
            name='leg_completion_estimation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phyloleg',
            name='leg_completion_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phyloleg',
            name='leg_directory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phyloanalog',
            name='leg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_set', to='phylomanager.phyloleg'),
        ),
        migrations.AlterField(
            model_name='phylorun',
            name='phylodata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phylomanager.phylodata'),
        ),
        migrations.AlterField(
            model_name='phylorun',
            name='run_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phylorun',
            name='run_status',
            field=models.CharField(blank=True, choices=[('DU', 'Data uploaded'), ('QD', 'Queued'), ('IP', 'In progress'), ('FN', 'Finished'), ('ER', 'Error occurred')], default='DU', max_length=10, null=True),
        ),
    ]
