# Generated by Django 4.0.4 on 2022-05-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NkfOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strat_unit', models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층')], max_length=10, null=True)),
                ('lithology', models.CharField(blank=True, choices=[('PR', 'Phosphatic rock'), ('ST', 'Siltstone'), ('LS', 'Limestone'), ('PS', 'Phosphatic siltstone'), ('SLST', 'Slate/Siltstone'), ('SS', 'Sandstone'), ('SC', 'Siliciclastic'), ('BS', 'Black slate'), ('BSLS', 'Black slate-limestone coupling'), ('SL', 'Slate'), ('LSDS', 'Limestone, dolostone'), ('DS', 'Dolostone'), ('MS', 'Mudstone'), ('PRLS', 'Phosphatic rock, limestone'), ('LSSL', 'Limestone, slate'), ('SLDS', 'Slate, dolostone')], max_length=10, null=True)),
                ('group', models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('BZ', 'bryozoan')], max_length=200, null=True)),
                ('species_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SH', '승호'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백')], max_length=10, null=True)),
            ],
        ),
    ]
