# Generated by Django 4.0.4 on 2022-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkfoccurrence',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='lithology',
            field=models.CharField(blank=True, choices=[('PR', 'phosphatic rock'), ('ST', 'siltstone'), ('LS', 'limestone'), ('PS', 'phosphatic siltstone'), ('SLST', 'slate/siltstone'), ('SS', 'sandstone'), ('SC', 'siliciclastic'), ('BS', 'Black slate'), ('BSLS', 'Black slate-limestone coupling'), ('SL', 'slate'), ('LSDS', 'limestone, dolostone'), ('DS', 'dolostone'), ('MS', 'mudstone'), ('PRLS', 'phosphatic rock, limestone'), ('LSSL', 'limestone, slate'), ('SLDS', 'slate, dolostone')], max_length=10, null=True),
        ),
    ]
