# Generated by Django 3.2.5 on 2022-05-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0002_nkfoccurrence_index_alter_nkfoccurrence_lithology'),
    ]

    operations = [
        migrations.CreateModel(
            name='NkfOccurrence2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('figure', models.CharField(blank=True, max_length=10, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('strat_range', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NkfOccurrence3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('publication', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.CharField(blank=True, max_length=10, null=True)),
                ('pages', models.CharField(blank=True, max_length=10, null=True)),
                ('geologic_period', models.CharField(blank=True, max_length=100, null=True)),
                ('fossil_group', models.CharField(blank=True, max_length=100, null=True)),
                ('fossil_group_code', models.CharField(blank=True, max_length=10, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('locality_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stratigraphy', models.CharField(blank=True, max_length=100, null=True)),
                ('stratigraphy_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lithology', models.CharField(blank=True, max_length=100, null=True)),
                ('figure', models.CharField(blank=True, max_length=100, null=True)),
                ('implication', models.CharField(blank=True, max_length=100, null=True)),
                ('titla', models.CharField(blank=True, max_length=500, null=True)),
                ('listed_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nkfoccurrence',
            name='genus_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nkfoccurrence',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
