# Generated by Django 3.2.5 on 2022-05-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0003_auto_20220511_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nkfoccurrence3',
            old_name='titla',
            new_name='title',
        ),
        migrations.AddField(
            model_name='nkfoccurrence3',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
