# Generated by Django 3.2.5 on 2022-05-13 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0004_auto_20220511_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='NkfLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nkfcluster.nkflocality')),
            ],
        ),
    ]
