# Generated by Django 3.2.5 on 2022-05-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0005_auto_20220513_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='NkfOccurrence4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('author1', models.CharField(blank=True, max_length=200, null=True)),
                ('author2', models.CharField(blank=True, max_length=200, null=True)),
                ('author3', models.CharField(blank=True, max_length=200, null=True)),
                ('author4', models.CharField(blank=True, max_length=200, null=True)),
                ('author_list', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('publication', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.CharField(blank=True, max_length=10, null=True)),
                ('pages', models.CharField(blank=True, max_length=10, null=True)),
                ('geologic_period', models.CharField(blank=True, max_length=100, null=True)),
                ('fossil_group', models.CharField(blank=True, max_length=100, null=True)),
                ('fossil_group_code', models.CharField(blank=True, max_length=10, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('locality_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stratigraphy', models.CharField(blank=True, max_length=100, null=True)),
                ('stratigraphy_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lithology', models.CharField(blank=True, max_length=100, null=True)),
                ('figure', models.CharField(blank=True, max_length=100, null=True)),
                ('implication', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('listed_species', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
