# Generated by Django 3.2.5 on 2022-06-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0006_nkfoccurrence4'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbdbOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occno', models.CharField(blank=True, max_length=50, null=True, verbose_name='PBDB OccurrenceNo')),
                ('collno', models.CharField(blank=True, max_length=50, null=True, verbose_name='PBDB CollectionNo')),
                ('species_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='종명')),
                ('genus_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='속명')),
                ('group', models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('BZ', 'bryozoan')], max_length=10, null=True)),
                ('max_ma', models.CharField(blank=True, max_length=10, null=True, verbose_name='From Ma')),
                ('min_ma', models.CharField(blank=True, max_length=10, null=True, verbose_name='To Ma')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='경도')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='위도')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='국가')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County')),
                ('formation', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='strat_unit',
            field=models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층')], max_length=10, null=True),
        ),
    ]
