# Generated by Django 3.2.5 on 2022-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0007_auto_20220609_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbdboccurrence',
            name='early_interval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='pbdboccurrence',
            name='late_interval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='To'),
        ),
    ]
