# Generated by Django 3.2.5 on 2022-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0008_auto_20220609_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbdboccurrence',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
    ]
