# Generated by Django 3.2.5 on 2022-06-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0009_pbdboccurrence_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('6', 'Supereon'), ('5', 'Eon'), ('4', 'Era'), ('3', 'Period'), ('2', 'Epoch'), ('1', 'Age')], max_length=1)),
                ('abbreviation', models.CharField(blank=True, max_length=200)),
                ('begin', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('end', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('terminal_unit_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nkfcluster.chronounit')),
            ],
            options={
                'ordering': ['begin'],
            },
        ),
    ]
