# Generated by Django 3.2.5 on 2022-06-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0010_chronounit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbdboccurrence',
            name='chrono_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChronoFrom', to='nkfcluster.chronounit', verbose_name='Chrono From'),
        ),
        migrations.AddField(
            model_name='pbdboccurrence',
            name='chrono_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChronoTo', to='nkfcluster.chronounit', verbose_name='Chrono To'),
        ),
    ]
