# Generated by Django 3.2.5 on 2022-06-13 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0011_auto_20220610_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('BZ', 'bryozoan')], max_length=200, null=True)),
                ('species_name', models.CharField(blank=True, max_length=200, null=True)),
                ('genus_name', models.CharField(blank=True, max_length=200, null=True)),
                ('locality_lvl1', models.CharField(blank=True, max_length=20, null=True)),
                ('locality_lvl2', models.CharField(blank=True, max_length=20, null=True)),
                ('locality_lvl3', models.CharField(blank=True, max_length=20, null=True)),
                ('chrono_lvl1', models.CharField(blank=True, max_length=20, null=True)),
                ('chrono_lvl2', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nkfoccurrence',
            name='chronounit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nkfcluster.chronounit'),
        ),
        migrations.AddField(
            model_name='pbdboccurrence',
            name='chrono_list',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='시대'),
        ),
        migrations.AlterField(
            model_name='chronounit',
            name='begin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chronounit',
            name='end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pbdboccurrence',
            name='max_ma',
            field=models.FloatField(blank=True, null=True, verbose_name='From Ma'),
        ),
        migrations.AlterField(
            model_name='pbdboccurrence',
            name='min_ma',
            field=models.FloatField(blank=True, null=True, verbose_name='To Ma'),
        ),
    ]
