# Generated by Django 3.2.5 on 2022-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0012_auto_20220613_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkfoccurrence',
            name='revised_genus_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nkfoccurrence',
            name='revised_species_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
