# Generated by Django 3.2.5 on 2022-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0013_auto_20220620_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbdboccurrence',
            name='revised_genus_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Revised 속명'),
        ),
        migrations.AddField(
            model_name='pbdboccurrence',
            name='revised_species_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Revised 종명'),
        ),
    ]
