# Generated by Django 3.2.5 on 2022-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0015_nkfoccurrence5'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkfoccurrence',
            name='source_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
