# Generated by Django 3.2.5 on 2022-06-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0016_nkfoccurrence_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pbdboccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totaloccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='NkfOccurrence1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('strat_unit', models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층')], max_length=10, null=True)),
                ('lithology', models.CharField(blank=True, choices=[('PR', 'phosphatic rock'), ('ST', 'siltstone'), ('LS', 'limestone'), ('PS', 'phosphatic siltstone'), ('SLST', 'slate/siltstone'), ('SS', 'sandstone'), ('SC', 'siliciclastic'), ('BS', 'Black slate'), ('BSLS', 'Black slate-limestone coupling'), ('SL', 'slate'), ('LSDS', 'limestone, dolostone'), ('DS', 'dolostone'), ('MS', 'mudstone'), ('PRLS', 'phosphatic rock, limestone'), ('LSSL', 'limestone, slate'), ('SLDS', 'slate, dolostone')], max_length=10, null=True)),
                ('group', models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates')], max_length=200, null=True)),
                ('species_name', models.CharField(blank=True, max_length=200, null=True)),
                ('genus_name', models.CharField(blank=True, max_length=200, null=True)),
                ('revised_species_name', models.CharField(blank=True, max_length=200, null=True)),
                ('revised_genus_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('source_code', models.CharField(blank=True, max_length=10, null=True)),
                ('chronounit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nkfcluster.chronounit')),
            ],
        ),
    ]
