# Generated by Django 3.2.5 on 2022-06-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0017_auto_20220622_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkfoccurrence5',
            name='from_chronounit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nkfoccurrence5',
            name='to_chronounit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='strat_unit',
            field=models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층'), ('SLS', '송림산주층'), ('LJG', '림진군층'), ('GS', '곡산주층'), ('SS', '상서주층'), ('JHG', '직현군층'), ('WY', '월양주층'), ('BA', '부압주층')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence1',
            name='strat_unit',
            field=models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층'), ('SLS', '송림산주층'), ('LJG', '림진군층'), ('GS', '곡산주층'), ('SS', '상서주층'), ('JHG', '직현군층'), ('WY', '월양주층'), ('BA', '부압주층')], max_length=10, null=True),
        ),
    ]
