# Generated by Django 3.2.5 on 2022-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0019_auto_20220623_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkfoccurrence5',
            name='lithology',
            field=models.CharField(blank=True, choices=[('PR', 'phosphatic rock'), ('ST', 'siltstone'), ('LS', 'limestone'), ('PS', 'phosphatic siltstone'), ('SLST', 'slate/siltstone'), ('SS', 'sandstone'), ('SC', 'siliciclastic'), ('BS', 'Black slate'), ('BSLS', 'Black slate-limestone coupling'), ('SL', 'slate'), ('LSDS', 'limestone, dolostone'), ('DS', 'dolostone'), ('MS', 'mudstone'), ('PRLS', 'phosphatic rock, limestone'), ('LSSL', 'limestone, slate'), ('SLDS', 'slate, dolostone'), ('CA', 'cabronate rock'), ('QZ', 'Quartzite')], max_length=100, null=True),
        ),
    ]
