# Generated by Django 3.2.5 on 2022-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0021_auto_20220624_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates'), ('AC', 'acritarch')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄'), ('JG', '중강')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='strat_unit',
            field=models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층'), ('SLS', '송림산주층'), ('LJG', '림진군층'), ('GS', '곡산주층'), ('SS', '상서주층'), ('JHG', '직현군층'), ('WY', '월양주층'), ('BA', '부압주층'), ('SDW', '사당우주층'), ('JN', '직현주층'), ('MC', '묵천주층'), ('MC2', '묵천층'), ('HJ', '홍점통'), ('RR', '릉리주층')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence1',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates'), ('AC', 'acritarch')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence1',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄'), ('JG', '중강')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence1',
            name='strat_unit',
            field=models.CharField(blank=True, choices=[('PS', '평산주층'), ('JH', '중화주층'), ('HG', '흑교주층'), ('LC', '림촌주층'), ('MJ', '무진주층'), ('GP', '고풍주층'), ('SG', '신곡주층'), ('MD', '만달주층'), ('BRD', '비랑동주층'), ('SLS', '송림산주층'), ('LJG', '림진군층'), ('GS', '곡산주층'), ('SS', '상서주층'), ('JHG', '직현군층'), ('WY', '월양주층'), ('BA', '부압주층'), ('SDW', '사당우주층'), ('JN', '직현주층'), ('MC', '묵천주층'), ('MC2', '묵천층'), ('HJ', '홍점통'), ('RR', '릉리주층')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pbdboccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates'), ('AC', 'acritarch')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='totaloccurrence',
            name='group',
            field=models.CharField(blank=True, choices=[('SP', 'sponge'), ('HY', 'hyolith'), ('TR', 'trilobite'), ('BR', 'brachiopod'), ('BD', 'bradoriid'), ('AG', 'algae'), ('PR', 'problematic'), ('HC', 'helcionelloid'), ('GA', 'gastropod'), ('CE', 'cephalopod'), ('CD', 'conodont'), ('CR', 'crinoid'), ('CA', 'coral'), ('BZ', 'bryozoan'), ('OS', 'ostracod'), ('PL', 'plants'), ('TF', 'trace fossils'), ('IV', 'invertebrates'), ('AC', 'acritarch')], max_length=200, null=True),
        ),
    ]
