# Generated by Django 3.2.5 on 2022-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0022_auto_20220627_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='NkfOccurrence6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('figure', models.CharField(blank=True, max_length=10, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('strat_range', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
