# Generated by Django 3.2.5 on 2022-06-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0023_nkfoccurrence6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nkfoccurrence',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄'), ('JG', '중강'), ('SG', '신계'), ('BC', '북창')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nkfoccurrence1',
            name='location',
            field=models.CharField(blank=True, choices=[('NP', '남포'), ('SL', '송림'), ('HJ', '황주'), ('SA', '수안'), ('GS', '곡산'), ('BD', '법동'), ('ERGI', '은률-과일'), ('PSGC', '평산-금천'), ('OJGR', '옹진-강령'), ('JHSW', '중화-상원'), ('SHSD', '승호-사동'), ('YSSP', '연산-신평'), ('GSGD', '강서-강동'), ('GCDCSC', '개천-덕천-순천'), ('GJ', '구장'), ('MS', '맹산'), ('ES', '은산'), ('GWCN', '고원-천내'), ('CSGP', '초산-고풍'), ('GGMP', '강계-만포'), ('HP', '화평'), ('JCSG', '전천-성간'), ('JJ', '장진'), ('BJ', '부전'), ('DH', '대흥'), ('SP', '신포'), ('HS', '혜산'), ('TB', '태백'), ('YT', '연탄'), ('JG', '중강'), ('SG', '신계'), ('BC', '북창')], max_length=10, null=True),
        ),
    ]
