# Generated by Django 3.2.5 on 2022-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0024_auto_20220628_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkfoccurrence',
            name='source_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
