# Generated by Django 3.2.5 on 2022-08-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0025_nkfoccurrence_source_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaloccurrence',
            name='source_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
