# Generated by Django 3.2.5 on 2023-05-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nkfcluster', '0026_totaloccurrence_source_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkflocality',
            name='terminal_unit_count',
            field=models.IntegerField(default=0),
        ),
    ]
