# Generated by Django 3.2.5 on 2022-05-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DolfinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=100)),
                ('md5hash', models.CharField(blank=True, default='', max_length=200)),
                ('imagefile', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
