# Generated by Django 3.2.5 on 2025-03-14 08:39

from django.db import migrations, models
import django.db.models.deletion
import siriuspasset.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpFossilSpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_no', models.CharField(db_index=True, help_text='개별 표본 식별 번호 (예: SP-2017-1-001)', max_length=100, verbose_name='표본 번호')),
                ('taxon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='학명')),
                ('phylum', models.CharField(blank=True, max_length=100, null=True, verbose_name='문(Phylum)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('counterpart', models.CharField(default=False, max_length=100, verbose_name='대응 표본')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 시각')),
                ('modified_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '화석 표본',
                'verbose_name_plural': '화석 표본 목록',
                'ordering': ['slab', 'specimen_no'],
            },
        ),
        migrations.CreateModel(
            name='SpSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_no', models.CharField(db_index=True, help_text='고유 슬랩 식별 번호 (예: SLAB-01)', max_length=100, unique=True, verbose_name='슬랩 번호')),
                ('counterpart', models.CharField(default=False, max_length=100, verbose_name='대응 슬랩')),
                ('horizon', models.CharField(blank=True, help_text='이 슬랩이 발견된 층준 정보', max_length=100, null=True, verbose_name='층준')),
                ('expedition_year', models.CharField(blank=True, help_text='이 슬랩이 발견된 탐사 연도', max_length=4, null=True, verbose_name='탐사연도')),
                ('location', models.CharField(blank=True, help_text='슬랩이 보관된 위치(수장고 정보 등)', max_length=100, null=True, verbose_name='보관 위치')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 시각')),
                ('modified_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '슬랩',
                'verbose_name_plural': '슬랩 목록',
                'ordering': ['slab_no'],
            },
        ),
        migrations.CreateModel(
            name='SpFossilSpecimenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='표본 사진 파일', upload_to=siriuspasset.models.fossil_image_upload_path)),
                ('description', models.TextField(blank=True, help_text='사진에 대한 설명 (예: 촬영 각도, 확대 배율 등)', null=True, verbose_name='설명')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 시각')),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('specimen', models.ForeignKey(help_text='이 이미지가 속한 화석 표본', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siriuspasset.spfossilspecimen')),
            ],
            options={
                'verbose_name': '화석 표본 사진',
                'verbose_name_plural': '화석 표본 사진 목록',
                'ordering': ['specimen', 'created_on'],
            },
        ),
        migrations.AddField(
            model_name='spfossilspecimen',
            name='slab',
            field=models.ForeignKey(help_text='해당 표본이 속한 슬랩(예:SP-2017-1)', on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='siriuspasset.spslab'),
        ),
        migrations.AlterUniqueTogether(
            name='spfossilspecimen',
            unique_together={('slab', 'specimen_no')},
        ),
    ]
