# Generated by Django 4.2.20 on 2025-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spfossilspecimenimage',
            name='md5hash',
            field=models.CharField(blank=True, db_index=True, help_text='이미지 파일의 MD5 해시값', max_length=32, null=True, verbose_name='MD5 해시'),
        ),
        migrations.AddField(
            model_name='spfossilspecimenimage',
            name='original_path',
            field=models.CharField(blank=True, help_text='원본 이미지 파일의 경로', max_length=500, null=True, verbose_name='원본 경로'),
        ),
        migrations.AddConstraint(
            model_name='spfossilspecimenimage',
            constraint=models.UniqueConstraint(condition=models.Q(('md5hash__isnull', False)), fields=('md5hash',), name='unique_image_hash'),
        ),
    ]
