# Generated by Django 4.2.7 on 2024-06-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0002_spfossilspecimenimage_md5hash_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpFossilSpecimenImage',
            new_name='SpFossilImage',
        ),
        migrations.AddField(
            model_name='spfossilimage',
            name='slab',
            field=models.ForeignKey(blank=True, help_text='이 이미지가 속한 슬랩', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siriuspasset.spslab'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='specimen',
            field=models.ForeignKey(blank=True, help_text='이 이미지가 속한 화석 표본', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siriuspasset.spfossilspecimen'),
        ),
        migrations.AddConstraint(
            model_name='spfossilimage',
            constraint=models.CheckConstraint(check=models.Q(('slab__isnull', False)) | models.Q(('specimen__isnull', False)), name='slab_or_specimen_not_null'),
        ),
    ] 