# Generated by Django 4.2.20 on 2025-03-18 01:40

from django.db import migrations, models
import siriuspasset.models


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0003_rename_spfossilspecimenimage_spfossilimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spfossilimage',
            options={'ordering': ['created_on'], 'verbose_name': '화석 사진', 'verbose_name_plural': '화석 사진 목록'},
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='image_file',
            field=models.ImageField(help_text='화석 사진 파일', upload_to=siriuspasset.models.fossil_image_upload_path),
        ),
    ]
