# Generated by Django 4.2.20 on 2025-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0004_alter_spfossilimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_directory', models.CharField(help_text='Path of the directory that was scanned', max_length=500, verbose_name='Scanned Directory')),
                ('scan_start_time', models.DateTimeField(auto_now_add=True, verbose_name='Scan Start Time')),
                ('scan_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Scan End Time')),
                ('scan_pattern', models.CharField(default='*', help_text='Pattern used to match files (e.g., SP-2016)', max_length=100, verbose_name='File Pattern')),
                ('total_files_found', models.IntegerField(default=0, verbose_name='Total Files Found')),
                ('new_images_imported', models.IntegerField(default=0, verbose_name='New Images Imported')),
                ('duplicate_images_skipped', models.IntegerField(default=0, verbose_name='Duplicate Images Skipped')),
                ('existing_images_skipped', models.IntegerField(default=0, verbose_name='Existing Images Skipped')),
                ('error_count', models.IntegerField(default=0, verbose_name='Errors Encountered')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=50, verbose_name='Status')),
                ('log_summary', models.TextField(blank=True, null=True, verbose_name='Log Summary')),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Directory Scan',
                'verbose_name_plural': 'Directory Scans',
                'ordering': ['-scan_start_time'],
            },
        ),
    ]
