# Generated by Django 4.2.20 on 2025-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0005_directoryscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryscan',
            name='older_files_skipped',
            field=models.IntegerField(default=0, help_text='Number of files skipped because they were created before the last scan', verbose_name='Older Files Skipped'),
        ),
    ]
