# Generated by Django 4.2.20 on 2025-03-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0006_auto_20250318_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spfossilimage',
            options={'ordering': ['created_on'], 'verbose_name': 'Fossil image', 'verbose_name_plural': 'Fossil images'},
        ),
        migrations.AddField(
            model_name='spfossilspecimen',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who created this record', null=True, verbose_name='Created IP'),
        ),
        migrations.AddField(
            model_name='spfossilspecimen',
            name='modified_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who last modified this record', null=True, verbose_name='Modified IP'),
        ),
        migrations.AddField(
            model_name='spslab',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who created this record', null=True, verbose_name='Created IP'),
        ),
        migrations.AddField(
            model_name='spslab',
            name='modified_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who last modified this record', null=True, verbose_name='Modified IP'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='duplicate_images_skipped',
            field=models.IntegerField(default=0, help_text='Number of duplicate images skipped', verbose_name='Duplicate Images Skipped'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Number of errors encountered', verbose_name='Errors Encountered'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='existing_images_skipped',
            field=models.IntegerField(default=0, help_text='Number of existing images skipped', verbose_name='Existing Images Skipped'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='log_summary',
            field=models.TextField(blank=True, default='', help_text='Summary of the scan log', verbose_name='Log Summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='new_images_imported',
            field=models.IntegerField(default=0, help_text='Number of new images imported', verbose_name='New Images Imported'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_directory',
            field=models.CharField(help_text='Path of the scanned directory', max_length=255, verbose_name='Scanned Directory'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_end_time',
            field=models.DateTimeField(blank=True, help_text='When the scan completed', null=True, verbose_name='Scan End Time'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_pattern',
            field=models.CharField(help_text='Pattern used to match files', max_length=50, verbose_name='File Pattern'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='When the scan started', verbose_name='Scan Start Time'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='total_files_found',
            field=models.IntegerField(default=0, help_text='Total image files found', verbose_name='Total Files Found'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='description',
            field=models.TextField(blank=True, help_text='사진에 대한 설명 (예: 촬영 각도, 확대 배율 등)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='md5hash',
            field=models.CharField(blank=True, db_index=True, help_text='이미지 파일의 MD5 해시값', max_length=32, null=True, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='spfossilimage',
            name='original_path',
            field=models.CharField(blank=True, help_text='원본 이미지 파일의 경로', max_length=500, null=True, verbose_name='Original path'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='counterpart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counterpart'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='phylum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phylum'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='specimen_no',
            field=models.CharField(db_index=True, help_text='개별 표본 식별 번호 (예: SP-2017-1-001)', max_length=100, verbose_name='Specimen number'),
        ),
        migrations.AlterField(
            model_name='spfossilspecimen',
            name='taxon_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxon name'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='counterpart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Counterpart'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='expedition_year',
            field=models.CharField(blank=True, help_text='이 슬랩이 발견된 탐사 연도', max_length=4, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='horizon',
            field=models.CharField(blank=True, help_text='이 슬랩이 발견된 층준 정보', max_length=100, null=True, verbose_name='Horizon'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='location',
            field=models.CharField(blank=True, help_text='슬랩이 보관된 위치(수장고 정보 등)', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='spslab',
            name='slab_no',
            field=models.CharField(db_index=True, help_text='고유 슬랩 식별 번호 (예: SLAB-01)', max_length=100, unique=True, verbose_name='Slab no.'),
        ),
    ]
