# Generated by Django 4.2.20 on 2025-03-19 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siriuspasset', '0007_alter_spfossilimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpSlab',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slab_no', models.CharField(db_index=True, help_text='고유 슬랩 식별 번호 (예: SLAB-01)', max_length=100, verbose_name='Slab no.')),
                ('counterpart', models.CharField(blank=True, max_length=100, null=True, verbose_name='Counterpart')),
                ('horizon', models.CharField(blank=True, help_text='이 슬랩이 발견된 층준 정보', max_length=100, null=True, verbose_name='Horizon')),
                ('expedition_year', models.CharField(blank=True, help_text='이 슬랩이 발견된 탐사 연도', max_length=4, null=True, verbose_name='Year')),
                ('location', models.CharField(blank=True, help_text='슬랩이 보관된 위치(수장고 정보 등)', max_length=100, null=True, verbose_name='Location')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='Created on')),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created this record', null=True, verbose_name='Created IP')),
                ('modified_on', models.DateTimeField(blank=True, editable=False, verbose_name='Modified on')),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user who last modified this record', null=True, verbose_name='Modified IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 슬랩',
                'verbose_name_plural': 'historical 슬랩 목록',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSpFossilSpecimen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('specimen_no', models.CharField(db_index=True, help_text='개별 표본 식별 번호 (예: SP-2017-1-001)', max_length=100, verbose_name='Specimen number')),
                ('taxon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxon name')),
                ('phylum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phylum')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('counterpart', models.CharField(blank=True, max_length=100, null=True, verbose_name='Counterpart')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='Created on')),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created this record', null=True, verbose_name='Created IP')),
                ('modified_on', models.DateTimeField(blank=True, editable=False, verbose_name='Modified on')),
                ('modified_by', models.CharField(blank=True, max_length=50)),
                ('modified_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user who last modified this record', null=True, verbose_name='Modified IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slab', models.ForeignKey(blank=True, db_constraint=False, help_text='해당 표본이 속한 슬랩(예:SP-2017-1)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='siriuspasset.spslab')),
            ],
            options={
                'verbose_name': 'historical 화석 표본',
                'verbose_name_plural': 'historical 화석 표본 목록',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
