# Generated by Django 4.2.20 on 2025-03-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siriuspasset', '0008_historicalspslab_historicalspfossilspecimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryscan',
            name='directory',
            field=models.CharField(default='', help_text='Directory scanned', max_length=512),
        ),
        migrations.AddField(
            model_name='directoryscan',
            name='images_created',
            field=models.IntegerField(default=0, help_text='Images successfully created'),
        ),
        migrations.AddField(
            model_name='directoryscan',
            name='images_found',
            field=models.IntegerField(default=0, help_text='Total image files found'),
        ),
        migrations.AddField(
            model_name='directoryscan',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix used for pattern matching', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='directoryscan',
            name='recursive',
            field=models.BooleanField(default=False, help_text='Whether subdirectories were scanned recursively'),
        ),
        migrations.AddField(
            model_name='directoryscan',
            name='year',
            field=models.CharField(blank=True, help_text='Year used for pattern matching', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='duplicate_images_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='existing_images_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='log_summary',
            field=models.TextField(blank=True, help_text='Summary of scan results', null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='new_images_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='older_files_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_end_time',
            field=models.DateTimeField(blank=True, help_text='When the scan completed', null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='scan_start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='When the scan was started'),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='directoryscan',
            name='total_files_found',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SpImageProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(help_text='Original file path when processed', max_length=512)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('md5hash', models.CharField(blank=True, help_text='MD5 hash of the file', max_length=32, null=True)),
                ('status', models.CharField(choices=[('success', 'Successfully Processed'), ('duplicate', 'Skipped as Duplicate'), ('no_match', 'No Pattern Match'), ('error', 'Error During Processing'), ('skipped', 'Skipped for Other Reason')], help_text='Processing outcome', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Details about processing outcome', null=True)),
                ('process_datetime', models.DateTimeField(auto_now_add=True, help_text='When the file was processed')),
                ('command_used', models.CharField(help_text='Command used for processing (import_specimens/scan_for_new_images)', max_length=50)),
                ('image', models.ForeignKey(blank=True, help_text='Link to created image if successful', null=True, on_delete=django.db.models.deletion.SET_NULL, to='siriuspasset.spfossilimage')),
                ('slab', models.ForeignKey(blank=True, help_text='Associated slab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='siriuspasset.spslab')),
                ('specimen', models.ForeignKey(blank=True, help_text='Associated specimen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='siriuspasset.spfossilspecimen')),
            ],
            options={
                'verbose_name': 'Image Processing Record',
                'verbose_name_plural': 'Image Processing Records',
                'indexes': [models.Index(fields=['original_path'], name='siriuspasse_origina_2d5330_idx'), models.Index(fields=['filename'], name='siriuspasse_filenam_89cf7b_idx'), models.Index(fields=['md5hash'], name='siriuspasse_md5hash_bb6d1b_idx'), models.Index(fields=['status'], name='siriuspasse_status_be3488_idx'), models.Index(fields=['process_datetime'], name='siriuspasse_process_d4501e_idx')],
            },
        ),
    ]
