# Generated by Django 3.2.5 on 2023-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0002_auto_20231127_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='roseoccurrence',
            name='distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roseoccurrence',
            name='length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
