# Generated by Django 3.2.5 on 2023-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0003_auto_20231127_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='roseoccurrence',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roseoccurrence',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roseoccurrence',
            name='rocktype1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roseoccurrence',
            name='rocktype2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roseoccurrence',
            name='symbol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
