# Generated by Django 4.2.20 on 2025-03-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DikeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200, null=True)),
                ('stratum', models.CharField(max_length=200, null=True)),
                ('rock_type', models.CharField(max_length=200, null=True)),
                ('era', models.CharField(max_length=200, null=True)),
                ('map_sheet', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('distance', models.FloatField(null=True)),
                ('angle', models.FloatField(null=True)),
                ('x_coord_1', models.FloatField(null=True)),
                ('y_coord_1', models.FloatField(null=True)),
                ('lat_1', models.FloatField(null=True)),
                ('lng_1', models.FloatField(null=True)),
                ('x_coord_2', models.FloatField(null=True)),
                ('y_coord_2', models.FloatField(null=True)),
                ('lat_2', models.FloatField(null=True)),
                ('lng_2', models.FloatField(null=True)),
                ('memo', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('result_message', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dike_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='dikesync.dikerecord')),
                ('sync_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dikesync.syncevent')),
            ],
            options={
                'unique_together': {('sync_event', 'dike_record')},
            },
        ),
    ]
