# Generated by Django 4.2.20 on 2025-03-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dikesync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dikerecord",
            name="unique_id",
            field=models.CharField(default="", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
