# Generated by Django 4.2.20 on 2025-03-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dikesync", "0002_dikerecord_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dikerecord",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dikerecord",
            name="last_sync_date",
            field=models.DateTimeField(null=True),
        ),
    ]
