# Generated by Django 4.2.20 on 2025-03-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dikesync", "0003_dikerecord_is_deleted_dikerecord_last_sync_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncevent",
            name="end_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name="SyncEventRecord",
        ),
    ]
